### ISSUE TITLE
Buffer error & Incorrect header check exceptions

### ISSUE THREAD

**Issue by dennisdevulder** [mikaelwikman/deluge-ruby#1]
After configuring my application and setting up the commands through my console there seems to be no issue. However after adding some torrents and listing them along with their progress percentage I keep getting the following log outputs:

buffer error
[".rvm/gems/ruby-2.1.2/gems/deluge-1.0.0/lib/deluge/protocol/v3.rb:157:in `inflate'", ".rvm/gems/ruby-2.1.2/gems/deluge-1.0.0/lib/deluge/protocol/v3.rb:157:in `handle_complete_message'", ".rvm/gems/ruby-2.1.2/gems/deluge-1.0.0/lib/deluge/protocol/v3.rb:139:in `handle_new_data'", ".rvm/gems/ruby-2.1.2/gems/deluge-1.0.0/lib/deluge/protocol/v3.rb:40:in `block (2 levels) in initialize'", ".rvm/gems/ruby-2.1.2/gems/deluge-1.0.0/lib/deluge/protocol/v3.rb:31:in `loop'", ".rvm/gems/ruby-2.1.2/gems/deluge-1.0.0/lib/deluge/protocol/v3.rb:31:in `block in initialize'"]

incorrect header check
[".rvm/gems/ruby-2.1.2/gems/deluge-1.0.0/lib/deluge/protocol/v3.rb:157:in `inflate'", ".rvm/gems/ruby-2.1.2/gems/deluge-1.0.0/lib/deluge/protocol/v3.rb:157:in `handle_complete_message'", ".rvm/gems/ruby-2.1.2/gems/deluge-1.0.0/lib/deluge/protocol/v3.rb:139:in `handle_new_data'", ".rvm/gems/ruby-2.1.2/gems/deluge-1.0.0/lib/deluge/protocol/v3.rb:40:in `block (2 levels) in initialize'", ".rvm/gems/ruby-2.1.2/gems/deluge-1.0.0/lib/deluge/protocol/v3.rb:31:in `loop'", ".rvm/gems/ruby-2.1.2/gems/deluge-1.0.0/lib/deluge/protocol/v3.rb:31:in `block in initialize'"]

With kind regards,
Dennis de Vulder

**Comment by t3hk0d3** [comment]
FYI: https://github.com/t3hk0d3/deluge-api

**Comment by Hidendra** [comment]
I ran into this myself as well and will submit a PR shortly for this to implement buffering.

**Comment by mikaelwikman** [comment]
Pull request merged, so I'll close this issue. @juozasg please re-open if this doesn't solve the problem.
